### ISSUE TITLE
dependencies for apex and nano bus. Maybe Hermit is your cup of tea

### ISSUE THREAD

**Issue by gedw99** [apexlang/apex-go#5]
great project. Like all projects i immediately hit dependency issues.

you might like hermit. It is not your average dependency system. 
https://github.com/cashapp/hermit

It can install rust and golang or anything that's a binary, but also products of them also like some binary.
It fully supports different OS and ARCH.
it can then fully manage the env and keep each repo your working on having only the versions of the binary dependences you want.
It also very fast... 
It seems like a god thing for all layers. so for nanonbus too, etc.

it will create a folder called "bin", and then mange all the binaries in there for you.
here is an example: https://github.com/cashapp/hermit/tree/master/bin

**Comment by pkedy** [comment]
@gedw99 This is definitely interesting. We NanoBus (and building Wasm modules) there are definitely a lot of toolchains to install which we've heard creates a lot of friction. It looks like Hermit could help bootstrap our prerequisites. Thanks for suggesting this!

**Comment by pkedy** [comment]
I'm going to close this issue and we will investigate.
